### ISSUE TITLE
[Import Error] with demo_videoqa.py

### ISSUE THREAD

**Issue by BigJoon** [antoyang/FrozenBiLM#13]
`python demo_videoqa.py --combine_datasets msrvtt --combine_datasets_val msrvtt --suffix="." --max_tokens=256 --ds_factor_ff=8 --ds_factor_attn=8 --load=checkpoints/frozenbilm_msrvtt10p.pth --msrvtt_vocab_path=data/MSRVTT-QA/vocab.json --question_example "what is that dog doing?" --video_example ./angry_cute_dog.mp4`

I downloaded all the data and checkpoints files. Also i downloaded transformers library from hugging face. But... plz.. check my error message..

`ImportError: cannot import name 'GreedySearchOutput' from 'transformers.generation_utils'(FrozenBiLM/transformers/src/transformers/generation_utils.py)`

what version of transformers library are u using?

**Comment by antoyang** [comment]
This is specified here: https://github.com/antoyang/FrozenBiLM/blob/main/requirements.txt

**Comment by BigJoon** [comment]
thanks! now i faced another problem now.. 

`Traceback (most recent call last):
  File "demo_videoqa.py", line 171, in <module>
    main(args)
  File "/opt/conda/envs/frozenbilm_env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "demo_videoqa.py", line 68, in main
    backbone, _ = clip.load("ViT-L/14", download_root=MODEL_DIR, device=device)
TypeError: load() got an unexpected keyword argument 'download_root'`

I already install "clip-by-openai" `pip install clip-by-openai`

why is this error happens..? Do you know anything about it?

**Comment by antoyang** [comment]
This is probably because the input feature is extracted/stored in half precision. Just doing video = video.float() should fix it.
